/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * Madhu Sethi Makeovers API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  "status": zod.string()
})


/**
 * @summary List all appointments
 */
export const ListAppointmentsQueryParams = zod.object({
  "status": zod.enum(['pending', 'confirmed', 'completed', 'cancelled']).optional(),
  "page": zod.coerce.number().optional(),
  "limit": zod.coerce.number().optional()
})

export const ListAppointmentsResponse = zod.object({
  "data": zod.array(zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "phone": zod.string(),
  "email": zod.string(),
  "service": zod.string(),
  "date": zod.string(),
  "time": zod.string(),
  "message": zod.string().nullish(),
  "status": zod.enum(['pending', 'confirmed', 'completed', 'cancelled']),
  "createdAt": zod.string()
})),
  "total": zod.number(),
  "page": zod.number().optional(),
  "limit": zod.number().optional()
})


/**
 * @summary Book a new appointment
 */
export const createAppointmentBodyNameMin = 2;

export const createAppointmentBodyPhoneMin = 10;



export const CreateAppointmentBody = zod.object({
  "name": zod.string().min(createAppointmentBodyNameMin),
  "phone": zod.string().min(createAppointmentBodyPhoneMin),
  "email": zod.string().email().or(zod.literal("")),
  "service": zod.string(),
  "date": zod.string(),
  "time": zod.string(),
  "message": zod.string().optional()
})


/**
 * @summary Get appointment by ID
 */
export const GetAppointmentParams = zod.object({
  "id": zod.coerce.number()
})

export const GetAppointmentResponse = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "phone": zod.string(),
  "email": zod.string(),
  "service": zod.string(),
  "date": zod.string(),
  "time": zod.string(),
  "message": zod.string().nullish(),
  "status": zod.enum(['pending', 'confirmed', 'completed', 'cancelled']),
  "createdAt": zod.string()
})


/**
 * @summary Update appointment status
 */
export const UpdateAppointmentParams = zod.object({
  "id": zod.coerce.number()
})

export const UpdateAppointmentBody = zod.object({
  "status": zod.enum(['pending', 'confirmed', 'completed', 'cancelled']).optional(),
  "message": zod.string().optional()
})

export const UpdateAppointmentResponse = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "phone": zod.string(),
  "email": zod.string(),
  "service": zod.string(),
  "date": zod.string(),
  "time": zod.string(),
  "message": zod.string().nullish(),
  "status": zod.enum(['pending', 'confirmed', 'completed', 'cancelled']),
  "createdAt": zod.string()
})


/**
 * @summary Delete appointment
 */
export const DeleteAppointmentParams = zod.object({
  "id": zod.coerce.number()
})


/**
 * @summary List all services
 */
export const ListServicesQueryParams = zod.object({
  "category": zod.coerce.string().optional()
})

export const ListServicesResponseItem = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "category": zod.enum(['bridal', 'party', 'hair', 'beauty']),
  "description": zod.string(),
  "price": zod.string().nullish(),
  "duration": zod.string(),
  "imageUrl": zod.string().nullish(),
  "featured": zod.boolean(),
  "sortOrder": zod.number(),
  "createdAt": zod.string()
})
export const ListServicesResponse = zod.array(ListServicesResponseItem)


/**
 * @summary Create a new service
 */
export const CreateServiceBody = zod.object({
  "name": zod.string(),
  "category": zod.enum(['bridal', 'party', 'hair', 'beauty']),
  "description": zod.string(),
  "price": zod.string().optional(),
  "duration": zod.string(),
  "imageUrl": zod.string().optional(),
  "featured": zod.boolean().optional(),
  "sortOrder": zod.number().optional()
})


/**
 * @summary Update a service
 */
export const UpdateServiceParams = zod.object({
  "id": zod.coerce.number()
})

export const UpdateServiceBody = zod.object({
  "name": zod.string().optional(),
  "category": zod.enum(['bridal', 'party', 'hair', 'beauty']).optional(),
  "description": zod.string().optional(),
  "price": zod.string().optional(),
  "duration": zod.string().optional(),
  "imageUrl": zod.string().optional(),
  "featured": zod.boolean().optional(),
  "sortOrder": zod.number().optional()
})

export const UpdateServiceResponse = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "category": zod.enum(['bridal', 'party', 'hair', 'beauty']),
  "description": zod.string(),
  "price": zod.string().nullish(),
  "duration": zod.string(),
  "imageUrl": zod.string().nullish(),
  "featured": zod.boolean(),
  "sortOrder": zod.number(),
  "createdAt": zod.string()
})


/**
 * @summary Delete a service
 */
export const DeleteServiceParams = zod.object({
  "id": zod.coerce.number()
})


/**
 * @summary List all testimonials
 */
export const ListTestimonialsQueryParams = zod.object({
  "featured": zod.coerce.boolean().optional(),
  "page": zod.coerce.number().optional(),
  "limit": zod.coerce.number().optional()
})

export const ListTestimonialsResponseItem = zod.object({
  "id": zod.number(),
  "clientName": zod.string(),
  "serviceType": zod.string().nullish(),
  "rating": zod.number(),
  "review": zod.string(),
  "imageUrl": zod.string().nullish(),
  "featured": zod.boolean(),
  "createdAt": zod.string()
})
export const ListTestimonialsResponse = zod.array(ListTestimonialsResponseItem)


/**
 * @summary Create a testimonial
 */
export const createTestimonialBodyRatingMax = 5;



export const CreateTestimonialBody = zod.object({
  "clientName": zod.string(),
  "serviceType": zod.string().optional(),
  "rating": zod.number().min(1).max(createTestimonialBodyRatingMax),
  "review": zod.string(),
  "imageUrl": zod.string().optional(),
  "featured": zod.boolean().optional()
})


/**
 * @summary Update a testimonial
 */
export const UpdateTestimonialParams = zod.object({
  "id": zod.coerce.number()
})

export const updateTestimonialBodyRatingMax = 5;



export const UpdateTestimonialBody = zod.object({
  "clientName": zod.string().optional(),
  "serviceType": zod.string().optional(),
  "rating": zod.number().min(1).max(updateTestimonialBodyRatingMax).optional(),
  "review": zod.string().optional(),
  "imageUrl": zod.string().optional(),
  "featured": zod.boolean().optional()
})

export const UpdateTestimonialResponse = zod.object({
  "id": zod.number(),
  "clientName": zod.string(),
  "serviceType": zod.string().nullish(),
  "rating": zod.number(),
  "review": zod.string(),
  "imageUrl": zod.string().nullish(),
  "featured": zod.boolean(),
  "createdAt": zod.string()
})


/**
 * @summary Delete a testimonial
 */
export const DeleteTestimonialParams = zod.object({
  "id": zod.coerce.number()
})


/**
 * @summary List gallery images
 */
export const ListGalleryImagesQueryParams = zod.object({
  "category": zod.coerce.string().optional(),
  "page": zod.coerce.number().optional(),
  "limit": zod.coerce.number().optional()
})

export const ListGalleryImagesResponseItem = zod.object({
  "id": zod.number(),
  "imageUrl": zod.string(),
  "altText": zod.string().nullish(),
  "category": zod.enum(['bridal', 'party', 'hair', 'transformations']),
  "featured": zod.boolean().optional(),
  "createdAt": zod.string()
})
export const ListGalleryImagesResponse = zod.array(ListGalleryImagesResponseItem)


/**
 * @summary Add a gallery image
 */
export const CreateGalleryImageBody = zod.object({
  "imageUrl": zod.string(),
  "altText": zod.string().optional(),
  "category": zod.enum(['bridal', 'party', 'hair', 'transformations']),
  "featured": zod.boolean().optional()
})


/**
 * @summary Delete a gallery image
 */
export const DeleteGalleryImageParams = zod.object({
  "id": zod.coerce.number()
})


/**
 * @summary List all contact messages
 */
export const ListMessagesQueryParams = zod.object({
  "read": zod.coerce.boolean().optional(),
  "page": zod.coerce.number().optional(),
  "limit": zod.coerce.number().optional()
})

export const ListMessagesResponseItem = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "phone": zod.string().nullable(),
  "email": zod.string(),
  "subject": zod.string().nullish(),
  "message": zod.string(),
  "read": zod.boolean(),
  "createdAt": zod.string()
})
export const ListMessagesResponse = zod.array(ListMessagesResponseItem)


/**
 * @summary Submit a contact message
 */
export const createMessageBodyNameMin = 2;

export const createMessageBodyMessageMin = 10;



export const CreateMessageBody = zod.object({
  "name": zod.string().min(createMessageBodyNameMin),
  "phone": zod.string().optional(),
  "email": zod.string().email(),
  "subject": zod.string().optional(),
  "message": zod.string().min(createMessageBodyMessageMin)
})


/**
 * @summary Mark message as read/unread
 */
export const UpdateMessageParams = zod.object({
  "id": zod.coerce.number()
})

export const UpdateMessageBody = zod.object({
  "read": zod.boolean().optional()
})

export const UpdateMessageResponse = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "phone": zod.string().nullable(),
  "email": zod.string(),
  "subject": zod.string().nullish(),
  "message": zod.string(),
  "read": zod.boolean(),
  "createdAt": zod.string()
})


/**
 * @summary Delete a message
 */
export const DeleteMessageParams = zod.object({
  "id": zod.coerce.number()
})


/**
 * @summary Get admin dashboard statistics
 */
export const GetDashboardStatsResponse = zod.object({
  "totalAppointments": zod.number(),
  "pendingAppointments": zod.number(),
  "confirmedAppointments": zod.number(),
  "completedAppointments": zod.number(),
  "totalMessages": zod.number(),
  "unreadMessages": zod.number(),
  "totalTestimonials": zod.number(),
  "totalServices": zod.number(),
  "totalGalleryImages": zod.number(),
  "recentAppointments": zod.array(zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "phone": zod.string(),
  "email": zod.string(),
  "service": zod.string(),
  "date": zod.string(),
  "time": zod.string(),
  "message": zod.string().nullish(),
  "status": zod.enum(['pending', 'confirmed', 'completed', 'cancelled']),
  "createdAt": zod.string()
}))
})

